# Puerto dinámico (OBLIGATORIO en cloud)
server.port=${PORT:8080}

spring.application.name=backend
# H2
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:postgresql://ecommerce_3x1l_user:ZLVnyTGlk9i1L5ftXt44ygKRy2HJjkV4@dpg-d7sf2j57vvec73davj3g-a/ecommerce_3x1l
spring.datasource.username=ecommerce_3x1l_user
spring.datasource.password=ZLVnyTGlk9i1L5ftXt44ygKRy2HJjkV4




spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Crear tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
# Desactivar consola H2 en producción (enabled=false)
spring.h2.console.enabled=false

logging.level.root=INFO
logging.level.com.ecommerce.backend=DEBUG
