# Puerto dinámico (cloud)
server.port=${PORT:8080}

spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d7sf2j57vvec73davj3g-a.oregon-postgres.render.com:5432/ecommerce_3x1l
spring.datasource.username=ecommerce_3x1l_user
spring.datasource.password=ZLVnyTGlk9i1L5ftXt44ygKRy2HJjkV4

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 desactivado
spring.h2.console.enabled=false

# Logs
logging.level.root=INFO
logging.level.com.ecommerce.backend=DEBUG